package main

import (
	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	_ "iot-mgmt/docs" // docs is generated by Swag CLI, you have to import it.
	"log"
	"os"
	"iot-mgmt/routers"
)

// @title iot management API
// @version 1.0
// @description This is a iot management server API.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8081
// @BasePath /api/v1
func main() {
	router := initEngine()
	port := os.Getenv("IOT_MGMT_SERVER_PORT")
	err := router.Run("0.0.0.0:" + port) // listen and serve on 0.0.0.0:8080
	if err != nil {
		log.Fatal(err)
	}
}

func initEngine() *gin.Engine {
	if err := godotenv.Load(); err != nil {
		log.Fatalln("Error loading .env file")
	}
	switch os.Getenv("env") {
	case "prod":
		gin.SetMode(gin.ReleaseMode)
	case "dev":
		fallthrough
	default:
		gin.SetMode(gin.DebugMode)
	}
	return routers.InitRouter()
}